# Generated by Django 3.0.3 on 2021-05-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('first_meme_likes', models.IntegerField()),
                ('second_meme_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='memes/%Y/%m/%d')),
                ('uploader', models.CharField(blank=True, default='oxecho', max_length=200)),
            ],
        ),
    ]
