# Generated by Django 3.0.3 on 2021-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.FileField(upload_to='memes_storage/%Y/%m/%d'),
        ),
    ]
