# Generated by Django 3.0.3 on 2021-05-14 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20210513_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='first_meme',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first_meme', to='memes.Meme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='second_meme',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_meme', to='memes.Meme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='likes',
            name='first_meme_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likes',
            name='second_meme_likes',
            field=models.IntegerField(default=0),
        ),
    ]
