# Generated by Django 3.0.3 on 2021-05-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20210514_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='first_meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_meme', to='memes.Meme'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='second_meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_meme', to='memes.Meme'),
        ),
    ]
