# Generated by Django 3.0.3 on 2021-05-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_auto_20210514_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(upload_to='memes_storage/%Y/%m/%d'),
        ),
    ]
