# Generated by Django 3.0.3 on 2021-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20210515_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='image_hash',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
