# Generated by Django 3.0.3 on 2021-05-16 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0007_auto_20210515_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('queued', 'Awaiting Approval'), ('declined', 'Declined')], default='approved', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
