# Generated by Django 3.0.3 on 2021-05-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_auto_20210516_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='approved',
        ),
        migrations.AddField(
            model_name='meme',
            name='approval',
            field=models.CharField(choices=[('approved', 'Approved'), ('queued', 'Awaiting Approval'), ('declined', 'Declined')], default='queued', max_length=50),
        ),
    ]
